name: openfashion
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_credit_card: ^4.1.0
  flutter_svg: ^2.2.3
  gap: ^3.0.1
  ionicons: ^0.2.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.0
flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter_test:
  sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/cover/
    - assets/logo/
    - assets/product/
    - assets/svgs/
    - assets/texts/
    - assets/pop/

  fonts:
    - family: "TenorSans"
      fonts:
        - asset: assets/fonts/Tenor_Sans/TenorSans-Regular.ttf
